#!/bin/sh
### BEGIN INIT INFO
# Provides:          service_3100
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Startup service plugin
# Description:       Startup service plugin
### END INIT INFO
#export PATH=$PATH:/usr/local/bin
#export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
# Include functions
set -e
. /lib/lsb/init-functions
cd /home/devil/front-end/server-side
start(){
       su -- devil -c "forever --pidFile pid_3100.pid start server_3100.js"
}

stop(){
       su -- devil -c "forever stop server_3100.js"
}

restart(){
        su -- devil -c "forever restart server_3100.js"
}

case "$1" in
        start)
                echo "Start service port 3100"
                start
                ;;
        stop)
                echo "Stop service port 3100"
                stop
                ;;
        restart)
                echo "Restart serviceport 3100"
                restart
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
                ;;
esac