#!/bin/sh
### BEGIN INIT INFO
# Provides:          service_3001
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Startup service file management
# Description:       Startup service file management
### END INIT INFO
#export PATH=$PATH:/usr/local/bin
#export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
# Include functions
set -e
. /lib/lsb/init-functions
cd /home/devil/front-end/file-manager/config
start(){
       su -- devil -c "forever --pidFile pid_3001.pid start server_3001.js"
}

stop(){
       su -- devil -c "forever stop server_3001.js"
}

restart(){
        su -- devil -c "forever restart server_3001.js"
}

case "$1" in
        start)
                echo "Start file management port 3001"
                start
                ;;
        stop)
                echo "Stop file management port 3001"
                stop
                ;;
        restart)
                echo "Restart file management port 3001"
                restart
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
                ;;
esac